Traceback (most recent call last):
  File "/home/rjanusia/.local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/rjanusia/.local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from config import deliver_files
from config import sx_f
from func_adl_servicex_xaodr22 import FuncADLQueryPHYSLITE, cpp_float, cpp_vfloat

import matplotlib.pyplot as plt
import numpy as np
import uproot
import awkward as ak
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mconfig[39;00m [38;5;28;01mimport[39;00m deliver_files
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mconfig[39;00m [38;5;28;01mimport[39;00m sx_f
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mfunc_adl_servicex_xaodr22[39;00m [38;5;28;01mimport[39;00m FuncADLQueryPHYSLITE, cpp_float, cpp_vfloat

[0;31mImportError[0m: cannot import name 'deliver_files' from 'config' (/home/rjanusia/WorkingDirectory/IrisHep/xaod_usage/book/chapters/config.py)

