Traceback (most recent call last):
  File "/home/rjanusia/.local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/rjanusia/.local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/rjanusia/.local/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pvs = (ds
       .Select(lambda e: e.Vertices("PrimaryVertices").First())
       .Select(lambda v:
       {
               "x": v.x(),
               "y": v.y(),
               "z": v.z(),
               "n": v.nTrackParticles(),
       })
       .AsAwkwardArray()
       .value())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m pvs [38;5;241m=[39m ([43mds[49m
[1;32m      2[0m        [38;5;241m.[39mSelect([38;5;28;01mlambda[39;00m e: e[38;5;241m.[39mVertices([38;5;124m"[39m[38;5;124mPrimaryVertices[39m[38;5;124m"[39m)[38;5;241m.[39mFirst())
[1;32m      3[0m        [38;5;241m.[39mSelect([38;5;28;01mlambda[39;00m v:
[1;32m      4[0m        {
[1;32m      5[0m                [38;5;124m"[39m[38;5;124mx[39m[38;5;124m"[39m: v[38;5;241m.[39mx(),
[1;32m      6[0m                [38;5;124m"[39m[38;5;124my[39m[38;5;124m"[39m: v[38;5;241m.[39my(),
[1;32m      7[0m                [38;5;124m"[39m[38;5;124mz[39m[38;5;124m"[39m: v[38;5;241m.[39mz(),
[1;32m      8[0m                [38;5;124m"[39m[38;5;124mn[39m[38;5;124m"[39m: v[38;5;241m.[39mnTrackParticles(),
[1;32m      9[0m        })
[1;32m     10[0m        [38;5;241m.[39mAsAwkwardArray()
[1;32m     11[0m        [38;5;241m.[39mvalue())

[0;31mNameError[0m: name 'ds' is not defined

